# Condensed MOM tracker content for slides 14-16 (faithful to source, trimmed for legibility)

S14 = [
 ["1","Design Coordination —\nPT Slab & MEP Cutouts",
  "PT slab design delayed by unresolved MEP sleeves, cutouts and openings. These must be coordinated before design completion; all consultants to sign off on drawings before proceeding.",
  "TPL — Rakesh Kumar Garg","For action",
  "All MEP cut-outs and sleeves incorporated in the B2 PT layout and approved by all consultants. B2 PT details issued to J+W on 10 Aug; comments received 13 and 21 Aug. GA layout resubmitted 25 Aug; PT tendon layout per peer-review comments submitted 31 Aug."],
 ["","Vendor & Consultant\nCoordination",
  "Performance shortfall from EcoFirst and Edifice; coordination issues persist despite multiple workshops and escalations. A rigorous workshop approach with direct TPL involvement was agreed.",
  "TPL — Rakesh Kumar Garg","For action",
  "TPL MEP team stationed at the EcoFirst office from 10 to 21 Aug to coordinate all B3 and B2 services and finalise the MEP input for the PT design."],
 ["","Workshop Planning &\nAction Items",
  "Focused discussions to be held twice weekly from the following week to identify grievances, shortfalls and support required, with EcoFirst and all consultants at the table.",
  "TPL — G V Radha Krishna","From 10 Aug 26",
  "Workshop held every Tuesday; additional sessions arranged as required."],
 ["","BIM versus 2D\nDesign Methodology",
  "BIM is used across all areas except Basements 1 and 2 of the 4-Star Hotel, where 2D drawings are an interim measure to expedite progress; those areas will be brought into BIM compliance later. Full multidisciplinary coordination is required before design sign-off.",
  "TPL — Rakesh Kumar Garg","For action","Agreed."],
]

S15 = [
 ["2","Detailed Design\nClosure",
  "Detailed Design is not closed — coordinated layouts and MEP-to-structural coordination remain outstanding.",
  "TPL — Rakesh Kumar Garg","For action",
  "Close coordination in progress. FAPA and Fire Fighting closed 26 Aug 26; Plumbing closed 27 Aug 26; Electrical and HVAC to close by 11 Sep 26."],
 ["","B3 Ceiling Layout",
  "Complete and finalise the Basement 3 ceiling coordinated layout by 15 August 2026.",
  "TPL — Rakesh Kumar Garg","15-08-26",
  "B3 ceiling coordinated with all consultants and submitted on 02 Sep 26."],
 ["","Design Input Tracker",
  "Prepare and present a tracker for all design inputs and clarifications to streamline communication across consultants.",
  "TPL — Sudhanshu Shukla","13-08-26","Tracker is being maintained."],
 ["","VE Façade Intent",
  "All clarifications on the updated VE façade intent agreed by stakeholders; the BIM model to be reshared with Edifice, with further coordination by TPL.",
  "ALACL / TPL","07-08-26","BIM model accepted by the Edifice team for further working."],
 ["","Meeting Agenda",
  "EcoFirst and Edifice meeting agenda points to be shared by TPL prior to the meeting.",
  "TPL — Rakesh Kumar Garg","For action","Noted."],
 ["","Landscape & External\nDevelopment",
  "Design cell to update the status of landscape and external development, coordinated with MEP works and completed.",
  "TPL — Sudhanshu Shukla","For action",
  "Landscape presentation held 27 Aug; Adani comments received the same day and are being coordinated."],
 ["","Utility Rooms",
  "Utility-room coordinated drawings to be completed within the same workshop.",
  "TPL — Sudhanshu Shukla","For action","Agreed."],
 ["","Leak-Proof Cut-Out",
  "TPL to share a typical detail of the leak-proof cut-out.",
  "TPL — Sudhanshu Shukla","21-08-26","Typical detail of the leak-proof cut-out submitted on 27 Aug 26."],
]

S16 = [
 ["3","Vendor List Submission\n& Approval",
  "Official vendor lists for all packages to be submitted by Monday without further discussion; critical packages must be awarded in the current quarter.",
  "TPL — G V Radha Krishna","For action","Submission made."],
 ["","Tendering & Technical\nEvaluation Workflow",
  "Workflow reviewed — design review, BOQ preparation, technical and commercial evaluation and work-order issue — with roles assigned to the cost consultant, PMC, D&B partner and other stakeholders.",
  "TPL — Vivek Srivastava","15-08-26","Noted; detailed information flow submitted."],
 ["","Package Strategy &\nSingle Contractor",
  "Single-contractor approach considered for certain MEP high-side and low-side works to streamline execution and reduce the risk of delay from contractor failure.",
  "TPL — Vivek Srivastava","13-08-26","Noted; the strategy as advised is being followed."],
 ["","RFP Finalisation",
  "STP, MEPF and Façade RFP documents to be finalised and vendors onboarded within this financial year, forming part of the FY cashflow.",
  "TPL / T&T / Adani","07-08-26",
  "RFPs for the various MEPF packages including STP submitted. Status tracker updated."],
 ["","NSC Vendor Onboarding",
  "TPL to submit independently its proposal for onboarding NSC vendors; all NSC package vendor lists were due on 10 Aug.",
  "TPL — Vivek Srivastava","For action","Submission made on 24 Aug 26."],
 ["4","Physical & Financial\nProgress Review",
  "Cumulative work done, budgeted cost and progress S-curves reviewed. Discrepancies between planned and actual progress noted, particularly in concrete and steel quantities, with acceleration strategies discussed.",
  "TPL — Vivek Srivastava","10-08-26",
  "Submitted through the Revamp Plan — mailed 04 Aug, discussed in detail 08 Aug and signed submission made 29 Aug 26."],
 ["","Resource & Quantity\nBreakdown",
  "Detailed breakdowns of reinforcement steel, concrete and other resources presented. Adani advised further analysis of monthly targets against actual achievement to ensure alignment with the schedule.",
  "TPL — Vivek Srivastava","For action","Noted."],
]
