# Condensed MOM tracker content for slides 14-16 (faithful to source, trimmed for legibility)

S14 = [
 ["1","Design Coordination —\nPT Slab & MEP Cutouts",
  "PT slab design delayed by unresolved MEP sleeves, cutouts and openings; all consultants to sign off before design completion.",
  "TPL — R. K. Garg","For action",
  "MEP cut-outs incorporated in the B2 PT layout and approved. B2 details issued to J+W 10 Aug; GA layout resubmitted 25 Aug; PT tendon layout submitted 31 Aug.","g"],
 ["","Vendor & Consultant\nCoordination",
  "Performance shortfall from EcoFirst and Edifice; a rigorous workshop approach with direct TPL involvement was agreed.",
  "TPL — R. K. Garg","For action",
  "TPL MEP team stationed at EcoFirst 10–21 Aug to coordinate B3 and B2 services and finalise PT input.","a"],
 ["","Workshop Planning &\nAction Items",
  "Focused discussions twice weekly to identify grievances, shortfalls and support required.",
  "TPL — G V Radha Krishna","From 10 Aug 26",
  "Workshop held every Tuesday; extra sessions as required.","g"],
 ["","BIM versus 2D\nDesign Methodology",
  "BIM used everywhere except 4-Star Basements 1 and 2, where 2D is an interim measure; those areas join BIM later.",
  "TPL — R. K. Garg","For action","Agreed.","g"],
]

S15 = [
 ["2","Detailed Design\nClosure",
  "DD not closed — coordinated layouts and MEP-to-structural coordination outstanding.",
  "TPL — R. K. Garg","For action",
  "FAPA and Fire Fighting closed 26 Aug; Plumbing 27 Aug; Electrical and HVAC by 11 Sep.","a"],
 ["","B3 Ceiling Layout",
  "Complete and finalise the Basement 3 ceiling coordinated layout by 15 August 2026.",
  "TPL — R. K. Garg","15-08-26",
  "Coordinated with all consultants and submitted 02 Sep 26.","g"],
 ["","Design Input Tracker",
  "Present a tracker for all design inputs and clarifications across consultants.",
  "TPL — S. Shukla","13-08-26","Tracker is being maintained.","g"],
 ["","VE Façade Intent",
  "VE façade intent agreed by all stakeholders; BIM model to be reshared with Edifice.",
  "ALACL / TPL","07-08-26","BIM model accepted by Edifice for further working.","g"],
 ["","Meeting Agenda",
  "EcoFirst and Edifice agenda points to be shared by TPL before the meeting.",
  "TPL — R. K. Garg","For action","Noted.","a"],
 ["","Landscape & External\nDevelopment",
  "Update landscape and external development status, coordinated with MEP works.",
  "TPL — S. Shukla","For action",
  "Presented 27 Aug; Adani comments being coordinated.","a"],
 ["","Utility Rooms",
  "Utility-room coordinated drawings to be completed in the same workshop.",
  "TPL — S. Shukla","For action","Agreed.","g"],
 ["","Leak-Proof Cut-Out",
  "TPL to share a typical detail of the leak-proof cut-out.",
  "TPL — S. Shukla","21-08-26","Typical detail submitted 27 Aug 26.","g"],
]

S16 = [
 ["3","Vendor List Submission\n& Approval",
  "Official vendor lists for all packages due Monday; critical packages to be awarded this quarter.",
  "TPL — G V Radha Krishna","For action","Submission made.","g"],
 ["","Tendering & Technical\nEvaluation",
  "Workflow reviewed — design review, BOQ, technical and commercial evaluation, work order.",
  "TPL — V. Srivastava","15-08-26","Noted; information flow submitted.","g"],
 ["","Package Strategy",
  "Single-contractor approach for certain MEP high-side and low-side works.",
  "TPL — V. Srivastava","13-08-26","Noted; strategy being followed.","g"],
 ["","RFP Finalisation",
  "STP, MEPF and Façade RFPs to be finalised and vendors onboarded this financial year.",
  "TPL / T&T / Adani","07-08-26","MEPF and STP RFPs submitted; tracker updated.","g"],
 ["","NSC Vendor Onboarding",
  "TPL to submit its own proposal for onboarding NSC vendors; lists due 10 Aug.",
  "TPL — V. Srivastava","For action","Submission made 24 Aug 26.","g"],
 ["4","Physical & Financial\nProgress Review",
  "Work done, budgeted cost and S-curves reviewed; concrete and steel shortfalls noted.",
  "TPL — V. Srivastava","10-08-26",
  "Revamp Plan mailed 04 Aug, discussed 08 Aug, signed 29 Aug 26.","g"],
 ["","Resource & Quantity\nBreakdown",
  "Steel, concrete and resource breakdowns presented; further analysis of monthly targets advised.",
  "TPL — V. Srivastava","For action","Noted.","a"],
]
